doctrine:
    dbal:
        default_connection: 'default'
        connections:
            default:
                application_name: telegram_bot_ca
                url: '%env(resolve:DATABASE_URL)%'
                schema_filter: '~^(?!tiger|%doctrine_table_queue%)~'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '14'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        second_level_cache:
            enabled: true
            region_lock_lifetime: 5
            region_cache_driver:
                type: pool
                pool: doctrine.second_level_cache_pool
            regions:
                minute_region:
                    cache_driver:
                        type: service
                        id: cache.app
                    lifetime: 60
                hour_region:
                    cache_driver:
                        type: service
                        id: cache.app
                    lifetime: 3600
                five_minute_region:
                    cache_driver:
                        type: service
                        id: cache.app
                    lifetime: 300
        metadata_cache_driver:
            type: pool
            pool: doctrine.meta_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.query_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
