version: '3.7'

networks:
  bot-platform:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    restart: unless-stopped
    labels:
      - bot-platform-app
    environment:
      COMPOSER_HOME: /var/www/.composer/app
    volumes:
      - ./:/var/www/app
#      - /dev/null:/etc/php/8.1/fpm/conf.d/10-opcache.ini:ro
#      - /dev/null:/etc/php/8.1/cli/conf.d/10-opcache.ini:ro
#      - ./etc/php/add-php-params.ini:/etc/php/8.1/fpm/conf.d/90-add-php-params.ini:ro
#      - ./etc/php/add-php-params.ini:/etc/php/8.1/cli/conf.d/90-add-php-params.ini:ro
#      - ./etc/php/docker-php-ext-xdebug.ini:/etc/php/8.1/fpm/conf.d/20-xdebug.ini:ro
      - /etc/localtime:/etc/localtime:ro
      - ./.docker/app/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:delegated
    expose:
      - "${PHP_FPM_EXPOSE_PORT}"
    depends_on:
      - db
      - rabbitmq
      - redis
    networks:
      - bot-platform

  redis:
    image: redis:latest
    ports:
      - "${FORWARD_REDIS_PORT}:6379"
    networks:
      - bot-platform

  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - ./.docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
#      - ./etc/nginx/conf/:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro
      - ./public:/var/www/app/public:ro
    expose:
      - "${NGINX_EXPOSE_PORT}"
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
    depends_on:
      - app
    networks:
      - bot-platform

  db:
    build:
      context: .
      dockerfile: ./.docker/postgresql/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PG_PORT}:${PG_EXPOSE_PORT}"
    expose:
      - "${PG_EXPOSE_PORT}"
    networks:
      - bot-platform

  rabbitmq:
    image: rabbitmq:3.12.1-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./.docker/rabbitmq/log/:/var/log/rabbitmq/
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - bot-platform